apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-audhd-lifecoach
  labels:
    app: audhd-lifecoach
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: audhd-lifecoach
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: audhd-lifecoach
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: PYTHONPATH
              value: /app
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: ENVIRONMENT
              value: {{ .Values.environment }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}