apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-audhd-lifecoach
  labels:
    app: audhd-lifecoach
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: audhd-lifecoach
    release: {{ .Release.Name }}