replicaCount: 1

image:
  repository: audhd-lifecoach
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

environment: development

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

ingress:
  enabled: false